### ISSUE TITLE
Como representar valores de moedas no schema

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/doacoes-comodatos-amigo-estado-mg#1]
Na última atualização da tabela de doações, apareceu um valor em euros. 

Segundo captei [nessa linha do script do repo da frictionless data specs](https://github.com/frictionlessdata/tableschema-js/blob/73455ea306df3008eaf4d3552edda47a162e8cdb/src/types/number.js#L21) , a propriedade bareNumber, quando setada para 'true', faria ler os valores das moedas. 

Entretanto, [a validação no goodtables não reconheceu a propriedade](https://goodtables.io/github/dados-mg/doacoes-comodatos-amigo-estado-mg/jobs/37) bareNumber da forma como foi colocada no schema.

[Este registro de atualização do table schema](https://datahub.io/blog/upgrade-to-data-package-specs-v1#table-schema) aponta que o 'bareNumber' foi substituído por 'currency', mas a [versão corrente da especificação](https://specs.frictionlessdata.io/table-schema/#number) ilustra o exemplo de uso para representar valores de moeda:

> The purpose of bareNumber is to allow publishers to publish numeric data that contains trailing characters such as percentages e.g. 95% or leading characters such as currencies e.g. €95 or EUR 95. Note that it is entirely up to implementors what, if anything, they do with stripped text.
format: no options (other than the default).

**Comment by fjuniorr** [comment]
@Andrelamor a propriedade `bareNumber` aceita um valor lógico `true` or `false`. Os valores `"true"` ou `"false"` são tratados como string por causa das aspas.

Lendo um dos issues que você referenciou (frictionlessdata/specs/issues/258) entendi que a propriedade `currency` que foi substituída pela `bareNumber` (decisão [aqui](https://github.com/frictionlessdata/specs/issues/258#issuecomment-313025489)). Isso inclusive faz mais sentido já que `currency` não está nas especificações. 

Voltando pro nosso problema. A `bareNumber` vai servir pra que uma string (ie. R$ 1700) seja interpretada como um número (ie. 1700), mas não gosto da idéia de usar isso para inserir o tipo da moeda na mesma coluna do valor. Vou copiar uma discussão do issue 258 relevante:

> Having read through several of the issues on the topic of numbers... may I make a suggestion?
> 
> Numbers should be numeric. Currencies and percentages are a type of unit, and these should be defined in the metadata, not the data. If it's really necessary to allow publishers to create bloated numeric data that won't parse properly using standard tools... then `bareNumber` seems like a reasonable option.
> 
> Side note: I would also advocate for the removal of `groupChar` (default: none) and either the removal of `decimalChar` (default: ".") or allow only "." or "," as possible values. See https://en.wikipedia.org/wiki/Decimal_mark#Current_standards.
> 
> -- https://github.com/frictionlessdata/specs/issues/258#issuecomment-315524883


> Some context: the reason for thinking about this so much is the experience of seeing so much data in the wild with this kind of info in it (e.g. a percentage sign or a currency etc). A big aim of the Data Package specs is to make it easier for average publishers to adopt it or for expert publishers to apply it to data they don't control. So think of properties like this as not representing what people SHOULD use but what they might HAVE to use to describe data that is getting produced by others (for example a major use of data packages is for fiscal data where the person "packaging" the data is having to use data produced upstream by someone else).
> 
> Re `groupChar` good point though once you're allowing it to be set I'm not sure it hurts to allow for more than those two values.
> 
> -- https://github.com/frictionlessdata/specs/issues/258#issuecomment-315674171

No nosso caso vejo dois encaminhamentos:

- Confirmar com a SEPLAG se na instrução processual o valor não foi eventualmente corrigido para real com alguma data base
- Em caso negativo, alterar o schema para inserir uma nova coluna que informa a moeda (vale a pena um google de como modelar isso, nunca tive experiência com esse tipo de situação)

Ps. Pra validação funcionar tem que ajustar a propriedade `format` em 

https://github.com/dados-mg/doacoes-comodatos-amigo-estado-mg/blob/d88c6e68ce99a3da026344fcaf32941c2032168f/datapackage.json#L73 

já que a especificação fala que "no options (other than the default)".

**Comment by Andrelamor** [comment]
Adicionei coluna para indicar a moeda, segundo padrão ISO, alterei propriedades da coluna VALOR, e registrei as mudanças no CHANGELOG: https://github.com/dados-mg/doacoes-comodatos-amigo-estado-mg/commit/9587e9d2d379d0e09a8774f59e01d564ac8f5d9b
